daysUntilStale: 15
daysUntilClose: 7
exemptLabels:
  - "discussion"
  - "feature request"
  - "bug"
  - "help wanted"
  - "plugin suggestion"
  - "good first issue"
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false
